services:

  #Zookeeper?? Nein, Deprecated. Finger weg.
  #zookeeper:
   # image: confluentinc/cp-zookeeper:7.0.0
    #ports:
     # - "2181:2181"
    #environment:
     # ZOOKEEPER_CLIENT_PORT: 2181

  #kafka:
    #image: confluentinc/cp-kafka:7.0.0 #Warum ist die Version 3 Jahre alt???? Gibt mittlerweile auch ein Package von Apache selbst ist
    #ports:
     # - "9092:9092"
    #hostname: kafka-server
    #environment:
      #KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 #Zookeeper ist deprecated
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #depends_on:
      #- zookeeper #Deprecated

  #Okay nur ein Node? Wollt ihr nicht ein Cluster haben? Aber von mir aus...
  #Vgl für Single Node: https://github.com/apache/kafka/blob/trunk/docker/examples/jvm/single-node/plaintext/docker-compose.yml
  kafka:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    networks:
      - kafka-netzwerk

  #UI erreichbar unter http://localhost:0808
  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:19092"
    ports:
      - 8080:8080
    links:
      - kafka
    networks:
      - kafka-netzwerk

networks:
  kafka-netzwerk: